name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    continue-on-error: ${{ matrix.experimental }}
    runs-on: "ubuntu-latest"
    name: "Tests | PHP ${{ matrix.php-version }} | Drupal ${{ matrix.drupal }}"
    strategy:
      matrix:
        experimental: [false]
        php-version:
          - "7.3"
        drupal:
          - "^8.9"
          - "^9.0"
        include:
          - php-version: "8.0"
            drupal: "^9.0"
            experimental: true
          - php-version: "8.1"
            drupal: "10.0.x-dev"
            experimental: true
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "xdebug"
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2
          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, gd
      - name: "Downgrade dev dependencies"
        run: "composer require phpunit/phpunit:6.5.14 drush/drush:~9 drupal/core-recommended:${{ matrix.drupal }} drupal/core-dev:${{ matrix.drupal }} --with-all-dependencies --dev --no-update"
        if: ${{ matrix.drupal == '^8.9' }}
      - name: "Upgrade to drupal/core:10.0.x and drush/drush:^11.0"
        run: "composer require drupal/core-recommended:${{ matrix.drupal }} drush/drush:^11.0 --with-all-dependencies --dev --no-update"
        if: ${{ matrix.drupal == '10.0.x-dev' }}
      - name: "Add phpspec/prophecy-phpunit"
        run: "composer require phpspec/prophecy-phpunit:^2 --dev --no-update"
        if: ${{ matrix.drupal != '^8.9' }}
      - name: "Install dependencies"
        run: "composer update --no-progress --prefer-dist"
      - name: "PHPUnit"
        run: "php vendor/bin/phpunit --debug"
